pipeline {
  agent any

  stages {
    stage('Run in Docker') {
      steps {
        bat 'docker pull node:16-alpine'
        bat 'docker run -d --name my-node-container node:16-alpine node --version'
      }
    }
  }
}
